name: SafeMark
platforms:
  iOS: 14.0
options:
  bundleIdPrefix: com.safemark
targets:
  SafeMark:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: .
        excludes:
          - "project.yml"
          - "SafeMark.xcodeproj"
    settings:
      base:
        DEVELOPMENT_TEAM: ""
        PRODUCT_BUNDLE_IDENTIFIER: com.safemark.app
        TARGETED_DEVICE_FAMILY: 1
        INFOPLIST_FILE: Info.plist
    info:
      path: Info.plist
      properties:
        UILaunchScreen: {}
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        NSPhotoLibraryUsageDescription: "需要访问您的相册以选择需要添加水印的图片"